### ISSUE TITLE
FindKF5DocTools error when running 'make rpi3_64-gui'

### ISSUE THREAD

**Issue by dickorydock** [OpenVoiceOS/ovos-buildroot#102] opened 2022-03-09 13:43 UTC
I am building for the RPi3 on Ubuntu 20.04 and wanted to share an error I got in case it is helpful for you all developing this great software. It seems kind of similar to the libGLESv4 issue mentioned in the documentation but not the same. 
```
Installing in /usr. Run /home/OpenVoiceOS/buildroot/output/build/kf5-kded-5.82.0/buildroot-build/prefix.sh to set the environment for KDED.


-- Looking for __GLIBC__
-- Looking for __GLIBC__ - found
-- Performing Test _OFFT_IS_64BIT
-- Performing Test _OFFT_IS_64BIT - Success
-- Performing Test HAVE_DATE_TIME
-- Performing Test HAVE_DATE_TIME - Success
CMake Warning at CMakeLists.txt:26 (find_package):
  By not providing "FindKF5DocTools.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "KF5DocTools", but CMake did not find one.

  Could not find a package configuration file provided by "KF5DocTools"
  (requested version 5.82.0) with any of the following names:

    KF5DocToolsConfig.cmake
    kf5doctools-config.cmake

  Add the installation prefix of "KF5DocTools" to CMAKE_PREFIX_PATH or set
  "KF5DocTools_DIR" to a directory containing one of the above files.  If
  "KF5DocTools" provides a separate development package or SDK, be sure it
  has been installed.


CMake Error at CMakeLists.txt:27 (find_package):
  By not providing "FindKF5Service.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "KF5Service", but CMake did not find one.

  Could not find a package configuration file provided by "KF5Service"
  (requested version 5.82.0) with any of the following names:

    KF5ServiceConfig.cmake
    kf5service-config.cmake

  Add the installation prefix of "KF5Service" to CMAKE_PREFIX_PATH or set
  "KF5Service_DIR" to a directory containing one of the above files.  If
  "KF5Service" provides a separate development package or SDK, be sure it has
  been installed.


-- Configuring incomplete, errors occurred!

```

**Comment by j1nx** [comment] 2022-03-09 16:08
Indeed! Ran into the same error, working on the x86_64 Open Virtual Appliance, however that work has not yet been pusjed or merged because it is wip.

For you to fix it, you can change;

diff --git a/buildroot-external/package/kf5-kded/kf5-kded.mk b/buildroot-external/package/kf5-kded/kf5-kded.mk
index c591c73..a375719 100644
--- a/buildroot-external/package/kf5-kded/kf5-kded.mk
+++ b/buildroot-external/package/kf5-kded/kf5-kded.mk
@@ -10,7 +10,7 @@ KF5_KDED_SOURCE = kded-$(KF5_KDED_VERSION).tar.xz
 KF5_KDED_LICENSE = BSD-3-Clause
 KF5_KDED_LICENSE_FILES = COPYING-CMAKE-SCRIPTS

-KF5_KDED_DEPENDENCIES = host-pkgconf
+KF5_KDED_DEPENDENCIES = host-pkgconf kf5-kservice
 KF5_KDED_INSTALL_STAGING = YES
 KF5_KDED_SUPPORTS_IN_SOURCE_BUILD = NO

Then rerun the "make rp3_64-gui" command.

**Comment by dickorydock** [comment] 2022-03-09 16:15
Thank you, that looks like it worked. I navigated to the file: buildroot-external/package/kf5-kded/kf5-kded.mk b/buildroot-external/package/kf5-kded/kf5-kded.mk

And there I changed
F5_KDED_DEPENDENCIES = host-pkgconf
to
F5_KDED_DEPENDENCIES = host-pkgconf kf5-kservice

It is running now, we will see. Thank you for the very quick resolution here

**Comment by j1nx** [comment] 2022-03-09 16:23
No worries. You might run into other problems further down the road, so let keep this issue open. Just report back when you got stuck.

**Comment by dickorydock** [comment] 2022-03-09 16:33
You are right, I already did :) Here is the error, let me know if I should make a separate Github issue:

```
Scanning dependencies of target remotedirnotify_autogen
[ 34%] Generating remotedirnotify.json
/bin/sh: 1: /home/OpenVoiceOS/buildroot/output/host/aarch64-buildroot-linux-gnu/sysroot/usr/bin/desktoptojson: Exec format error
make[5]: *** [src/ioslaves/remote/kdedmodule/CMakeFiles/remotedirnotify_autogen.dir/build.make:62: src/ioslaves/remote/kdedmodule/remotedirnotify.json] Error 2
make[4]: *** [CMakeFiles/Makefile2:1579: src/ioslaves/remote/kdedmodule/CMakeFiles/remotedirnotify_autogen.dir/all] Error 2
make[4]: *** Waiting for unfinished jobs....
[ 34%] Built target kio_remote_autogen
[ 34%] Built target KF5KIOGui_autogen
[ 34%] Built target kcm_trash_autogen
[ 34%] Built target kio_trash_autogen
make[3]: *** [Makefile:130: all] Error 2
make[2]: *** [package/pkg-generic.mk:250: /home/OpenVoiceOS/buildroot/output/build/kf5-kio-5.82.0/.stamp_built] Error 2
make[1]: *** [Makefile:84: _all] Error 2
make[1]: Leaving directory '/home/OpenVoiceOS/buildroot'
#cp -f buildroot/output/images/sdcard.img release/OpenVoiceOS_rpi3_64-gui.img
rsync -ah --progress buildroot/output/images/sdcard.img release/OpenVoiceOS_rpi3_64-gui.img
sending incremental file list
rsync: link_stat "/home/OpenVoiceOS/buildroot/output/images/sdcard.img" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1207) [sender=3.1.3]
make: *** [Makefile:27: rpi3_64-gui] Error 23

```

**Comment by j1nx** [comment] 2022-03-09 18:19
Ah right, that error is still there as well. Crap.

Will post a quick fix to get past it a little bit later today.

**Comment by j1nx** [comment] 2022-03-09 20:43
Apologies, it will take a bit longer as I am trying to reproduce the error again.

**Comment by dickorydock** [comment] 2022-03-09 20:46
That's fine! Take your time. Let me know if there's other information I can provide in the meanwhile. Thanks

**Comment by dickorydock** [comment] 2022-04-06 04:53
Hello, checking if there are any updates on this error. Thank you.

**Comment by RedB00t** [comment] 2022-06-13 00:26
Found this thread due to having the same issue as above.... just posting to see if there is an update and thank you for all that you do!

**Comment by NHellFire** [comment] 2023-04-14 13:43
For the desktoptojson issue, you'll need to install the system package providing it (for Debian flavours, that's libkf5coreaddons-dev-bin). I'm currently looking at getting that built by buildroot instead. Same for kf5-kconfig (then #128 won't be needed).

**Comment by j1nx** [comment] 2023-04-21 09:51
> For the desktoptojson issue, you'll need to install the system package providing it (for Debian flavours, that's libkf5coreaddons-dev-bin). I'm currently looking at getting that built by buildroot instead. Same for kf5-kconfig (then #128 won't be needed).

I hope you figure out a smart way to do this indeed as buildroot host package, however buildroot does not have a QT5 host package so when I tried it ended up in a rabbithole.

**Comment by j1nx** [comment] 2023-12-29 08:15
no longer needed

**Closed as completed by j1nx** 2023-12-29 08:15 UTC
